/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BatchInstance" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BatchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CurrentUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ExecutedModules" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LocalFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ReviewOperatorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ValidateOperatorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UncSubFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RemoteBatchInstanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ServerIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchInstance"
})
@XmlRootElement(name = "BatchInstances")
public class BatchInstances
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "BatchInstance")
    protected List<BatchInstances.BatchInstance> batchInstance;

    /**
     * Gets the value of the batchInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batchInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchInstances.BatchInstance }
     * 
     * 
     */
    public List<BatchInstances.BatchInstance> getBatchInstance() {
        if (batchInstance == null) {
            batchInstance = new ArrayList<BatchInstances.BatchInstance>();
        }
        return this.batchInstance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BatchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CurrentUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ExecutedModules" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LocalFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ReviewOperatorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ValidateOperatorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UncSubFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RemoteBatchInstanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ServerIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batchName",
        "currentUser",
        "executedModules",
        "localFolder",
        "reviewOperatorName",
        "validateOperatorName",
        "identifier",
        "uncSubFolder",
        "remoteBatchInstanceId",
        "serverIP"
    })
    public static class BatchInstance
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "BatchName", required = true)
        protected String batchName;
        @XmlElement(name = "CurrentUser", required = true)
        protected String currentUser;
        @XmlElement(name = "ExecutedModules", required = true)
        protected String executedModules;
        @XmlElement(name = "LocalFolder", required = true)
        protected String localFolder;
        @XmlElement(name = "ReviewOperatorName", required = true)
        protected String reviewOperatorName;
        @XmlElement(name = "ValidateOperatorName", required = true)
        protected String validateOperatorName;
        @XmlElement(name = "Identifier", required = true)
        protected String identifier;
        @XmlElement(name = "UncSubFolder", required = true)
        protected String uncSubFolder;
        @XmlElement(name = "RemoteBatchInstanceId", required = true)
        protected String remoteBatchInstanceId;
        @XmlElement(name = "ServerIP", required = true)
        protected String serverIP;

        /**
         * Gets the value of the batchName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBatchName() {
            return batchName;
        }

        /**
         * Sets the value of the batchName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBatchName(String value) {
            this.batchName = value;
        }

        /**
         * Gets the value of the currentUser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrentUser() {
            return currentUser;
        }

        /**
         * Sets the value of the currentUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrentUser(String value) {
            this.currentUser = value;
        }

        /**
         * Gets the value of the executedModules property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExecutedModules() {
            return executedModules;
        }

        /**
         * Sets the value of the executedModules property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExecutedModules(String value) {
            this.executedModules = value;
        }

        /**
         * Gets the value of the localFolder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalFolder() {
            return localFolder;
        }

        /**
         * Sets the value of the localFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalFolder(String value) {
            this.localFolder = value;
        }

        /**
         * Gets the value of the reviewOperatorName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReviewOperatorName() {
            return reviewOperatorName;
        }

        /**
         * Sets the value of the reviewOperatorName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReviewOperatorName(String value) {
            this.reviewOperatorName = value;
        }

        /**
         * Gets the value of the validateOperatorName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidateOperatorName() {
            return validateOperatorName;
        }

        /**
         * Sets the value of the validateOperatorName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidateOperatorName(String value) {
            this.validateOperatorName = value;
        }

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifier(String value) {
            this.identifier = value;
        }

        /**
         * Gets the value of the uncSubFolder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUncSubFolder() {
            return uncSubFolder;
        }

        /**
         * Sets the value of the uncSubFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUncSubFolder(String value) {
            this.uncSubFolder = value;
        }

        /**
         * Gets the value of the remoteBatchInstanceId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemoteBatchInstanceId() {
            return remoteBatchInstanceId;
        }

        /**
         * Sets the value of the remoteBatchInstanceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemoteBatchInstanceId(String value) {
            this.remoteBatchInstanceId = value;
        }

        /**
         * Gets the value of the serverIP property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerIP() {
            return serverIP;
        }

        /**
         * Sets the value of the serverIP property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerIP(String value) {
            this.serverIP = value;
        }

    }

}
