/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BatchInstanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchClassIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchInstanceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *         &lt;element name="BatchClassDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchClassVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchPriority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchStatus" type="{http://www.ephesoft.com/batch/batchStatus}batchStatus"/>
 *         &lt;element name="BatchCreationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BatchLocalPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrentModule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UNCFolderPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentClassificationTypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentClassificationType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Documents">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Document" type="{}document" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BatchLevelFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BatchLevelField" type="{}batchLevelField" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchInstanceIdentifier",
    "batchClassIdentifier",
    "batchInstanceDescription",
    "userName",
    "batchClassName",
    "signature",
    "batchClassDescription",
    "batchClassVersion",
    "batchName",
    "batchDescription",
    "batchPriority",
    "batchStatus",
    "batchCreationDate",
    "batchLocalPath",
    "currentModule",
    "uncFolderPath",
    "documentClassificationTypes",
    "documents",
    "batchLevelFields"
})
@XmlRootElement(name = "Batch")
public class Batch
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "BatchInstanceIdentifier", required = true)
    protected String batchInstanceIdentifier;
    @XmlElement(name = "BatchClassIdentifier", required = true)
    protected String batchClassIdentifier;
    @XmlElement(name = "BatchInstanceDescription", required = true)
    protected String batchInstanceDescription;
    @XmlElement(name = "UserName", required = true)
    protected String userName;
    @XmlElement(name = "BatchClassName", required = true)
    protected String batchClassName;
    @XmlElement(name = "Signature", required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] signature;
    @XmlElement(name = "BatchClassDescription", required = true)
    protected String batchClassDescription;
    @XmlElement(name = "BatchClassVersion", required = true)
    protected String batchClassVersion;
    @XmlElement(name = "BatchName", required = true)
    protected String batchName;
    @XmlElement(name = "BatchDescription", required = true)
    protected String batchDescription;
    @XmlElement(name = "BatchPriority", required = true)
    protected String batchPriority;
    @XmlElement(name = "BatchStatus", required = true)
    protected BatchStatus batchStatus;
    @XmlElement(name = "BatchCreationDate", required = true)
    protected String batchCreationDate;
    @XmlElement(name = "BatchLocalPath", required = true)
    protected String batchLocalPath;
    @XmlElement(name = "CurrentModule", required = true)
    protected String currentModule;
    @XmlElement(name = "UNCFolderPath", required = true)
    protected String uncFolderPath;
    @XmlElement(name = "DocumentClassificationTypes", required = true)
    protected Batch.DocumentClassificationTypes documentClassificationTypes;
    @XmlElement(name = "Documents", required = true)
    protected Batch.Documents documents;
    @XmlElement(name = "BatchLevelFields", required = true)
    protected Batch.BatchLevelFields batchLevelFields;

    /**
     * Gets the value of the batchInstanceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchInstanceIdentifier() {
        return batchInstanceIdentifier;
    }

    /**
     * Sets the value of the batchInstanceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchInstanceIdentifier(String value) {
        this.batchInstanceIdentifier = value;
    }

    /**
     * Gets the value of the batchClassIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchClassIdentifier() {
        return batchClassIdentifier;
    }

    /**
     * Sets the value of the batchClassIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchClassIdentifier(String value) {
        this.batchClassIdentifier = value;
    }

    /**
     * Gets the value of the batchInstanceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchInstanceDescription() {
        return batchInstanceDescription;
    }

    /**
     * Sets the value of the batchInstanceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchInstanceDescription(String value) {
        this.batchInstanceDescription = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the batchClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchClassName() {
        return batchClassName;
    }

    /**
     * Sets the value of the batchClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchClassName(String value) {
        this.batchClassName = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignature(byte[] value) {
        this.signature = ((byte[]) value);
    }

    /**
     * Gets the value of the batchClassDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchClassDescription() {
        return batchClassDescription;
    }

    /**
     * Sets the value of the batchClassDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchClassDescription(String value) {
        this.batchClassDescription = value;
    }

    /**
     * Gets the value of the batchClassVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchClassVersion() {
        return batchClassVersion;
    }

    /**
     * Sets the value of the batchClassVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchClassVersion(String value) {
        this.batchClassVersion = value;
    }

    /**
     * Gets the value of the batchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchName() {
        return batchName;
    }

    /**
     * Sets the value of the batchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchName(String value) {
        this.batchName = value;
    }

    /**
     * Gets the value of the batchDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchDescription() {
        return batchDescription;
    }

    /**
     * Sets the value of the batchDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchDescription(String value) {
        this.batchDescription = value;
    }

    /**
     * Gets the value of the batchPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchPriority() {
        return batchPriority;
    }

    /**
     * Sets the value of the batchPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchPriority(String value) {
        this.batchPriority = value;
    }

    /**
     * Gets the value of the batchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BatchStatus }
     *     
     */
    public BatchStatus getBatchStatus() {
        return batchStatus;
    }

    /**
     * Sets the value of the batchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchStatus }
     *     
     */
    public void setBatchStatus(BatchStatus value) {
        this.batchStatus = value;
    }

    /**
     * Gets the value of the batchCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchCreationDate() {
        return batchCreationDate;
    }

    /**
     * Sets the value of the batchCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchCreationDate(String value) {
        this.batchCreationDate = value;
    }

    /**
     * Gets the value of the batchLocalPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchLocalPath() {
        return batchLocalPath;
    }

    /**
     * Sets the value of the batchLocalPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchLocalPath(String value) {
        this.batchLocalPath = value;
    }

    /**
     * Gets the value of the currentModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentModule() {
        return currentModule;
    }

    /**
     * Sets the value of the currentModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentModule(String value) {
        this.currentModule = value;
    }

    /**
     * Gets the value of the uncFolderPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNCFolderPath() {
        return uncFolderPath;
    }

    /**
     * Sets the value of the uncFolderPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNCFolderPath(String value) {
        this.uncFolderPath = value;
    }

    /**
     * Gets the value of the documentClassificationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Batch.DocumentClassificationTypes }
     *     
     */
    public Batch.DocumentClassificationTypes getDocumentClassificationTypes() {
        return documentClassificationTypes;
    }

    /**
     * Sets the value of the documentClassificationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Batch.DocumentClassificationTypes }
     *     
     */
    public void setDocumentClassificationTypes(Batch.DocumentClassificationTypes value) {
        this.documentClassificationTypes = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link Batch.Documents }
     *     
     */
    public Batch.Documents getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Batch.Documents }
     *     
     */
    public void setDocuments(Batch.Documents value) {
        this.documents = value;
    }

    /**
     * Gets the value of the batchLevelFields property.
     * 
     * @return
     *     possible object is
     *     {@link Batch.BatchLevelFields }
     *     
     */
    public Batch.BatchLevelFields getBatchLevelFields() {
        return batchLevelFields;
    }

    /**
     * Sets the value of the batchLevelFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Batch.BatchLevelFields }
     *     
     */
    public void setBatchLevelFields(Batch.BatchLevelFields value) {
        this.batchLevelFields = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BatchLevelField" type="{}batchLevelField" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batchLevelField"
    })
    public static class BatchLevelFields
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "BatchLevelField")
        protected List<BatchLevelField> batchLevelField;

        /**
         * Gets the value of the batchLevelField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the batchLevelField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBatchLevelField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BatchLevelField }
         * 
         * 
         */
        public List<BatchLevelField> getBatchLevelField() {
            if (batchLevelField == null) {
                batchLevelField = new ArrayList<BatchLevelField>();
            }
            return this.batchLevelField;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentClassificationType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentClassificationType"
    })
    public static class DocumentClassificationTypes
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "DocumentClassificationType")
        protected List<String> documentClassificationType;

        /**
         * Gets the value of the documentClassificationType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentClassificationType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentClassificationType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDocumentClassificationType() {
            if (documentClassificationType == null) {
                documentClassificationType = new ArrayList<String>();
            }
            return this.documentClassificationType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Document" type="{}document" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "document"
    })
    public static class Documents
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "Document")
        protected List<Document> document;

        /**
         * Gets the value of the document property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the document property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document }
         * 
         * 
         */
        public List<Document> getDocument() {
            if (document == null) {
                document = new ArrayList<Document>();
            }
            return this.document;
        }

    }

}
