/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Confidence" type="{}confidence"/>
 *         &lt;element name="ConfidenceThreshold" type="{}confidence"/>
 *         &lt;element name="Valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Reviewed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentDisplayInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreviousType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentLevelFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentLevelField" type="{}docField" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pages">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Page" type="{}page" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataTables">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataTable" type="{}dataTable" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MultiPageTiffFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MultiPagePdfFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FinalMultiPagePdfFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FinalMultiPageTiffFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "document", propOrder = {
    "identifier",
    "type",
    "description",
    "size",
    "confidence",
    "confidenceThreshold",
    "valid",
    "reviewed",
    "errorMessage",
    "documentDisplayInfo",
    "previousType",
    "documentLevelFields",
    "pages",
    "dataTables",
    "multiPageTiffFile",
    "multiPagePdfFile",
    "finalMultiPagePdfFilePath",
    "finalMultiPageTiffFilePath"
})
public class Document
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "Identifier", required = true)
    protected String identifier;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Size", required = true)
    protected String size;
    @XmlElement(name = "Confidence")
    protected float confidence;
    @XmlElement(name = "ConfidenceThreshold")
    protected float confidenceThreshold;
    @XmlElement(name = "Valid")
    protected boolean valid;
    @XmlElement(name = "Reviewed")
    protected boolean reviewed;
    @XmlElement(name = "ErrorMessage", required = true)
    protected String errorMessage;
    @XmlElement(name = "DocumentDisplayInfo", required = true, defaultValue = "")
    protected String documentDisplayInfo;
    @XmlElement(name = "PreviousType", required = true)
    protected String previousType;
    @XmlElement(name = "DocumentLevelFields", required = true)
    protected Document.DocumentLevelFields documentLevelFields;
    @XmlElement(name = "Pages", required = true)
    protected Document.Pages pages;
    @XmlElement(name = "DataTables", required = true)
    protected Document.DataTables dataTables;
    @XmlElement(name = "MultiPageTiffFile", required = true)
    protected String multiPageTiffFile;
    @XmlElement(name = "MultiPagePdfFile", required = true)
    protected String multiPagePdfFile;
    @XmlElement(name = "FinalMultiPagePdfFilePath", required = true)
    protected String finalMultiPagePdfFilePath;
    @XmlElement(name = "FinalMultiPageTiffFilePath", required = true)
    protected String finalMultiPageTiffFilePath;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     */
    public float getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     */
    public void setConfidence(float value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the confidenceThreshold property.
     * 
     */
    public float getConfidenceThreshold() {
        return confidenceThreshold;
    }

    /**
     * Sets the value of the confidenceThreshold property.
     * 
     */
    public void setConfidenceThreshold(float value) {
        this.confidenceThreshold = value;
    }

    /**
     * Gets the value of the valid property.
     * 
     */
    public boolean isValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     */
    public void setValid(boolean value) {
        this.valid = value;
    }

    /**
     * Gets the value of the reviewed property.
     * 
     */
    public boolean isReviewed() {
        return reviewed;
    }

    /**
     * Sets the value of the reviewed property.
     * 
     */
    public void setReviewed(boolean value) {
        this.reviewed = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the documentDisplayInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentDisplayInfo() {
        return documentDisplayInfo;
    }

    /**
     * Sets the value of the documentDisplayInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentDisplayInfo(String value) {
        this.documentDisplayInfo = value;
    }

    /**
     * Gets the value of the previousType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousType() {
        return previousType;
    }

    /**
     * Sets the value of the previousType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousType(String value) {
        this.previousType = value;
    }

    /**
     * Gets the value of the documentLevelFields property.
     * 
     * @return
     *     possible object is
     *     {@link Document.DocumentLevelFields }
     *     
     */
    public Document.DocumentLevelFields getDocumentLevelFields() {
        return documentLevelFields;
    }

    /**
     * Sets the value of the documentLevelFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document.DocumentLevelFields }
     *     
     */
    public void setDocumentLevelFields(Document.DocumentLevelFields value) {
        this.documentLevelFields = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link Document.Pages }
     *     
     */
    public Document.Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document.Pages }
     *     
     */
    public void setPages(Document.Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the dataTables property.
     * 
     * @return
     *     possible object is
     *     {@link Document.DataTables }
     *     
     */
    public Document.DataTables getDataTables() {
        return dataTables;
    }

    /**
     * Sets the value of the dataTables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document.DataTables }
     *     
     */
    public void setDataTables(Document.DataTables value) {
        this.dataTables = value;
    }

    /**
     * Gets the value of the multiPageTiffFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiPageTiffFile() {
        return multiPageTiffFile;
    }

    /**
     * Sets the value of the multiPageTiffFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiPageTiffFile(String value) {
        this.multiPageTiffFile = value;
    }

    /**
     * Gets the value of the multiPagePdfFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiPagePdfFile() {
        return multiPagePdfFile;
    }

    /**
     * Sets the value of the multiPagePdfFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiPagePdfFile(String value) {
        this.multiPagePdfFile = value;
    }

    /**
     * Gets the value of the finalMultiPagePdfFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalMultiPagePdfFilePath() {
        return finalMultiPagePdfFilePath;
    }

    /**
     * Sets the value of the finalMultiPagePdfFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalMultiPagePdfFilePath(String value) {
        this.finalMultiPagePdfFilePath = value;
    }

    /**
     * Gets the value of the finalMultiPageTiffFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalMultiPageTiffFilePath() {
        return finalMultiPageTiffFilePath;
    }

    /**
     * Sets the value of the finalMultiPageTiffFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalMultiPageTiffFilePath(String value) {
        this.finalMultiPageTiffFilePath = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataTable" type="{}dataTable" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataTable"
    })
    public static class DataTables
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "DataTable")
        protected List<DataTable> dataTable;

        /**
         * Gets the value of the dataTable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataTable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataTable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataTable }
         * 
         * 
         */
        public List<DataTable> getDataTable() {
            if (dataTable == null) {
                dataTable = new ArrayList<DataTable>();
            }
            return this.dataTable;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentLevelField" type="{}docField" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentLevelField"
    })
    public static class DocumentLevelFields
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "DocumentLevelField")
        protected List<DocField> documentLevelField;

        /**
         * Gets the value of the documentLevelField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentLevelField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentLevelField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocField }
         * 
         * 
         */
        public List<DocField> getDocumentLevelField() {
            if (documentLevelField == null) {
                documentLevelField = new ArrayList<DocField>();
            }
            return this.documentLevelField;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Page" type="{}page" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "page"
    })
    public static class Pages
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "Page")
        protected List<Page> page;

        /**
         * Gets the value of the page property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the page property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Page }
         * 
         * 
         */
        public List<Page> getPage() {
            if (page == null) {
                page = new ArrayList<Page>();
            }
            return this.page;
        }

    }

}
