/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Params" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AdvancedKV" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="LocationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NoOfWords" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Multiplier" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="KeyPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ValuePattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="KVFetchValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Xoffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Yoffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="KeyFuzziness" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "params"
})
@XmlRootElement(name = "ExtractKVParams")
public class ExtractKVParams
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "Params")
    protected List<ExtractKVParams.Params> params;

    /**
     * Gets the value of the params property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the params property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtractKVParams.Params }
     * 
     * 
     */
    public List<ExtractKVParams.Params> getParams() {
        if (params == null) {
            params = new ArrayList<ExtractKVParams.Params>();
        }
        return this.params;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AdvancedKV" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="LocationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NoOfWords" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Multiplier" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="KeyPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ValuePattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="KVFetchValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Xoffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Yoffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="KeyFuzziness" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "advancedKV",
        "locationType",
        "noOfWords",
        "multiplier",
        "keyPattern",
        "valuePattern",
        "kvFetchValue",
        "length",
        "width",
        "xoffset",
        "yoffset",
        "weight",
        "keyFuzziness"
    })
    public static class Params
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "AdvancedKV", defaultValue = "false")
        protected boolean advancedKV;
        @XmlElement(name = "LocationType", required = true)
        protected String locationType;
        @XmlElement(name = "NoOfWords")
        protected int noOfWords;
        @XmlElement(name = "Multiplier", defaultValue = "1")
        protected float multiplier;
        @XmlElement(name = "KeyPattern", required = true)
        protected String keyPattern;
        @XmlElement(name = "ValuePattern", required = true)
        protected String valuePattern;
        @XmlElement(name = "KVFetchValue", required = true)
        protected String kvFetchValue;
        @XmlElement(name = "Length")
        protected int length;
        @XmlElement(name = "Width")
        protected int width;
        @XmlElement(name = "Xoffset")
        protected int xoffset;
        @XmlElement(name = "Yoffset")
        protected int yoffset;
        @XmlElement(name = "Weight", defaultValue = "1")
        protected float weight;
        @XmlElement(name = "KeyFuzziness", required = true, type = Float.class, nillable = true)
        protected Float keyFuzziness;

        /**
         * Gets the value of the advancedKV property.
         * 
         */
        public boolean isAdvancedKV() {
            return advancedKV;
        }

        /**
         * Sets the value of the advancedKV property.
         * 
         */
        public void setAdvancedKV(boolean value) {
            this.advancedKV = value;
        }

        /**
         * Gets the value of the locationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocationType() {
            return locationType;
        }

        /**
         * Sets the value of the locationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocationType(String value) {
            this.locationType = value;
        }

        /**
         * Gets the value of the noOfWords property.
         * 
         */
        public int getNoOfWords() {
            return noOfWords;
        }

        /**
         * Sets the value of the noOfWords property.
         * 
         */
        public void setNoOfWords(int value) {
            this.noOfWords = value;
        }

        /**
         * Gets the value of the multiplier property.
         * 
         */
        public float getMultiplier() {
            return multiplier;
        }

        /**
         * Sets the value of the multiplier property.
         * 
         */
        public void setMultiplier(float value) {
            this.multiplier = value;
        }

        /**
         * Gets the value of the keyPattern property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKeyPattern() {
            return keyPattern;
        }

        /**
         * Sets the value of the keyPattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKeyPattern(String value) {
            this.keyPattern = value;
        }

        /**
         * Gets the value of the valuePattern property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuePattern() {
            return valuePattern;
        }

        /**
         * Sets the value of the valuePattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuePattern(String value) {
            this.valuePattern = value;
        }

        /**
         * Gets the value of the kvFetchValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKVFetchValue() {
            return kvFetchValue;
        }

        /**
         * Sets the value of the kvFetchValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKVFetchValue(String value) {
            this.kvFetchValue = value;
        }

        /**
         * Gets the value of the length property.
         * 
         */
        public int getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         */
        public void setLength(int value) {
            this.length = value;
        }

        /**
         * Gets the value of the width property.
         * 
         */
        public int getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(int value) {
            this.width = value;
        }

        /**
         * Gets the value of the xoffset property.
         * 
         */
        public int getXoffset() {
            return xoffset;
        }

        /**
         * Sets the value of the xoffset property.
         * 
         */
        public void setXoffset(int value) {
            this.xoffset = value;
        }

        /**
         * Gets the value of the yoffset property.
         * 
         */
        public int getYoffset() {
            return yoffset;
        }

        /**
         * Sets the value of the yoffset property.
         * 
         */
        public void setYoffset(int value) {
            this.yoffset = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public float getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(float value) {
            this.weight = value;
        }

        /**
         * Gets the value of the keyFuzziness property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getKeyFuzziness() {
            return keyFuzziness;
        }

        /**
         * Sets the value of the keyFuzziness property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setKeyFuzziness(Float value) {
            this.keyFuzziness = value;
        }

    }

}
