/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImportIfConflict" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ZipFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UseExisting" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UncFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UseSource" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RolesImported" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="EmailAccounts" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CmisPlugin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="cmisPluginProperties" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="cmisMappings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UseKey" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="BatchClassKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EncryptionAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="importConnections" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="BatchClassDefinition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Scripts" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Script" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Folders" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Folder" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BatchClassModules" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BatchClassModule" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ModuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PluginConfiguration" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "importIfConflict",
    "zipFilePath",
    "useExisting",
    "uncFolder",
    "useSource",
    "name",
    "description",
    "priority",
    "rolesImported",
    "emailAccounts",
    "cmisPlugin",
    "cmisPluginProperties",
    "cmisMappings",
    "useKey",
    "batchClassKey",
    "encryptionAlgorithm",
    "importConnections",
    "batchClassDefinition"
})
@XmlRootElement(name = "ImportBatchClassOptions")
public class ImportBatchClassOptions
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "ImportIfConflict", defaultValue = "false")
    protected boolean importIfConflict;
    @XmlElement(name = "ZipFilePath", required = true)
    protected String zipFilePath;
    @XmlElement(name = "UseExisting", defaultValue = "false")
    protected boolean useExisting;
    @XmlElement(name = "UncFolder", required = true)
    protected String uncFolder;
    @XmlElement(name = "UseSource", defaultValue = "false")
    protected boolean useSource;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Priority")
    protected int priority;
    @XmlElement(name = "RolesImported", defaultValue = "false")
    protected boolean rolesImported;
    @XmlElement(name = "EmailAccounts", defaultValue = "false")
    protected boolean emailAccounts;
    @XmlElement(name = "CmisPlugin", defaultValue = "false")
    protected boolean cmisPlugin;
    @XmlElement(defaultValue = "false")
    protected boolean cmisPluginProperties;
    @XmlElement(defaultValue = "false")
    protected boolean cmisMappings;
    @XmlElement(name = "UseKey", defaultValue = "false")
    protected boolean useKey;
    @XmlElement(name = "BatchClassKey", required = true)
    protected String batchClassKey;
    @XmlElement(name = "EncryptionAlgorithm", required = true)
    protected String encryptionAlgorithm;
    protected boolean importConnections;
    @XmlElement(name = "BatchClassDefinition")
    protected List<ImportBatchClassOptions.BatchClassDefinition> batchClassDefinition;

    /**
     * Gets the value of the importIfConflict property.
     * 
     */
    public boolean isImportIfConflict() {
        return importIfConflict;
    }

    /**
     * Sets the value of the importIfConflict property.
     * 
     */
    public void setImportIfConflict(boolean value) {
        this.importIfConflict = value;
    }

    /**
     * Gets the value of the zipFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipFilePath() {
        return zipFilePath;
    }

    /**
     * Sets the value of the zipFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipFilePath(String value) {
        this.zipFilePath = value;
    }

    /**
     * Gets the value of the useExisting property.
     * 
     */
    public boolean isUseExisting() {
        return useExisting;
    }

    /**
     * Sets the value of the useExisting property.
     * 
     */
    public void setUseExisting(boolean value) {
        this.useExisting = value;
    }

    /**
     * Gets the value of the uncFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUncFolder() {
        return uncFolder;
    }

    /**
     * Sets the value of the uncFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUncFolder(String value) {
        this.uncFolder = value;
    }

    /**
     * Gets the value of the useSource property.
     * 
     */
    public boolean isUseSource() {
        return useSource;
    }

    /**
     * Sets the value of the useSource property.
     * 
     */
    public void setUseSource(boolean value) {
        this.useSource = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the rolesImported property.
     * 
     */
    public boolean isRolesImported() {
        return rolesImported;
    }

    /**
     * Sets the value of the rolesImported property.
     * 
     */
    public void setRolesImported(boolean value) {
        this.rolesImported = value;
    }

    /**
     * Gets the value of the emailAccounts property.
     * 
     */
    public boolean isEmailAccounts() {
        return emailAccounts;
    }

    /**
     * Sets the value of the emailAccounts property.
     * 
     */
    public void setEmailAccounts(boolean value) {
        this.emailAccounts = value;
    }

    /**
     * Gets the value of the cmisPlugin property.
     * 
     */
    public boolean isCmisPlugin() {
        return cmisPlugin;
    }

    /**
     * Sets the value of the cmisPlugin property.
     * 
     */
    public void setCmisPlugin(boolean value) {
        this.cmisPlugin = value;
    }

    /**
     * Gets the value of the cmisPluginProperties property.
     * 
     */
    public boolean isCmisPluginProperties() {
        return cmisPluginProperties;
    }

    /**
     * Sets the value of the cmisPluginProperties property.
     * 
     */
    public void setCmisPluginProperties(boolean value) {
        this.cmisPluginProperties = value;
    }

    /**
     * Gets the value of the cmisMappings property.
     * 
     */
    public boolean isCmisMappings() {
        return cmisMappings;
    }

    /**
     * Sets the value of the cmisMappings property.
     * 
     */
    public void setCmisMappings(boolean value) {
        this.cmisMappings = value;
    }

    /**
     * Gets the value of the useKey property.
     * 
     */
    public boolean isUseKey() {
        return useKey;
    }

    /**
     * Sets the value of the useKey property.
     * 
     */
    public void setUseKey(boolean value) {
        this.useKey = value;
    }

    /**
     * Gets the value of the batchClassKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchClassKey() {
        return batchClassKey;
    }

    /**
     * Sets the value of the batchClassKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchClassKey(String value) {
        this.batchClassKey = value;
    }

    /**
     * Gets the value of the encryptionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionAlgorithm() {
        return encryptionAlgorithm;
    }

    /**
     * Sets the value of the encryptionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionAlgorithm(String value) {
        this.encryptionAlgorithm = value;
    }

    /**
     * Gets the value of the importConnections property.
     * 
     */
    public boolean isImportConnections() {
        return importConnections;
    }

    /**
     * Sets the value of the importConnections property.
     * 
     */
    public void setImportConnections(boolean value) {
        this.importConnections = value;
    }

    /**
     * Gets the value of the batchClassDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batchClassDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchClassDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImportBatchClassOptions.BatchClassDefinition }
     * 
     * 
     */
    public List<ImportBatchClassOptions.BatchClassDefinition> getBatchClassDefinition() {
        if (batchClassDefinition == null) {
            batchClassDefinition = new ArrayList<ImportBatchClassOptions.BatchClassDefinition>();
        }
        return this.batchClassDefinition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Scripts" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Script" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Folders" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Folder" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BatchClassModules" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BatchClassModule" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ModuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PluginConfiguration" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scripts",
        "folders",
        "batchClassModules"
    })
    public static class BatchClassDefinition
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "Scripts")
        protected ImportBatchClassOptions.BatchClassDefinition.Scripts scripts;
        @XmlElement(name = "Folders")
        protected ImportBatchClassOptions.BatchClassDefinition.Folders folders;
        @XmlElement(name = "BatchClassModules")
        protected ImportBatchClassOptions.BatchClassDefinition.BatchClassModules batchClassModules;

        /**
         * Gets the value of the scripts property.
         * 
         * @return
         *     possible object is
         *     {@link ImportBatchClassOptions.BatchClassDefinition.Scripts }
         *     
         */
        public ImportBatchClassOptions.BatchClassDefinition.Scripts getScripts() {
            return scripts;
        }

        /**
         * Sets the value of the scripts property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImportBatchClassOptions.BatchClassDefinition.Scripts }
         *     
         */
        public void setScripts(ImportBatchClassOptions.BatchClassDefinition.Scripts value) {
            this.scripts = value;
        }

        /**
         * Gets the value of the folders property.
         * 
         * @return
         *     possible object is
         *     {@link ImportBatchClassOptions.BatchClassDefinition.Folders }
         *     
         */
        public ImportBatchClassOptions.BatchClassDefinition.Folders getFolders() {
            return folders;
        }

        /**
         * Sets the value of the folders property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImportBatchClassOptions.BatchClassDefinition.Folders }
         *     
         */
        public void setFolders(ImportBatchClassOptions.BatchClassDefinition.Folders value) {
            this.folders = value;
        }

        /**
         * Gets the value of the batchClassModules property.
         * 
         * @return
         *     possible object is
         *     {@link ImportBatchClassOptions.BatchClassDefinition.BatchClassModules }
         *     
         */
        public ImportBatchClassOptions.BatchClassDefinition.BatchClassModules getBatchClassModules() {
            return batchClassModules;
        }

        /**
         * Sets the value of the batchClassModules property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImportBatchClassOptions.BatchClassDefinition.BatchClassModules }
         *     
         */
        public void setBatchClassModules(ImportBatchClassOptions.BatchClassDefinition.BatchClassModules value) {
            this.batchClassModules = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BatchClassModule" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ModuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PluginConfiguration" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "batchClassModule"
        })
        public static class BatchClassModules
            implements Serializable
        {

            private final static long serialVersionUID = 100L;
            @XmlElement(name = "BatchClassModule")
            protected List<ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule> batchClassModule;

            /**
             * Gets the value of the batchClassModule property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the batchClassModule property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBatchClassModule().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule }
             * 
             * 
             */
            public List<ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule> getBatchClassModule() {
                if (batchClassModule == null) {
                    batchClassModule = new ArrayList<ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule>();
                }
                return this.batchClassModule;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ModuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PluginConfiguration" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "moduleName",
                "pluginConfiguration"
            })
            public static class BatchClassModule
                implements Serializable
            {

                private final static long serialVersionUID = 100L;
                @XmlElement(name = "ModuleName", required = true)
                protected String moduleName;
                @XmlElement(name = "PluginConfiguration", defaultValue = "false")
                protected boolean pluginConfiguration;

                /**
                 * Gets the value of the moduleName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModuleName() {
                    return moduleName;
                }

                /**
                 * Sets the value of the moduleName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModuleName(String value) {
                    this.moduleName = value;
                }

                /**
                 * Gets the value of the pluginConfiguration property.
                 * 
                 */
                public boolean isPluginConfiguration() {
                    return pluginConfiguration;
                }

                /**
                 * Sets the value of the pluginConfiguration property.
                 * 
                 */
                public void setPluginConfiguration(boolean value) {
                    this.pluginConfiguration = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Folder" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "folder"
        })
        public static class Folders
            implements Serializable
        {

            private final static long serialVersionUID = 100L;
            @XmlElement(name = "Folder")
            protected List<ImportBatchClassOptions.BatchClassDefinition.Folders.Folder> folder;

            /**
             * Gets the value of the folder property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the folder property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFolder().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ImportBatchClassOptions.BatchClassDefinition.Folders.Folder }
             * 
             * 
             */
            public List<ImportBatchClassOptions.BatchClassDefinition.Folders.Folder> getFolder() {
                if (folder == null) {
                    folder = new ArrayList<ImportBatchClassOptions.BatchClassDefinition.Folders.Folder>();
                }
                return this.folder;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileName",
                "selected"
            })
            public static class Folder
                implements Serializable
            {

                private final static long serialVersionUID = 100L;
                @XmlElement(name = "FileName", required = true)
                protected String fileName;
                @XmlElement(name = "Selected", defaultValue = "false")
                protected boolean selected;

                /**
                 * Gets the value of the fileName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFileName() {
                    return fileName;
                }

                /**
                 * Sets the value of the fileName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFileName(String value) {
                    this.fileName = value;
                }

                /**
                 * Gets the value of the selected property.
                 * 
                 */
                public boolean isSelected() {
                    return selected;
                }

                /**
                 * Sets the value of the selected property.
                 * 
                 */
                public void setSelected(boolean value) {
                    this.selected = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Script" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "script"
        })
        public static class Scripts
            implements Serializable
        {

            private final static long serialVersionUID = 100L;
            @XmlElement(name = "Script")
            protected List<ImportBatchClassOptions.BatchClassDefinition.Scripts.Script> script;

            /**
             * Gets the value of the script property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the script property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getScript().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ImportBatchClassOptions.BatchClassDefinition.Scripts.Script }
             * 
             * 
             */
            public List<ImportBatchClassOptions.BatchClassDefinition.Scripts.Script> getScript() {
                if (script == null) {
                    script = new ArrayList<ImportBatchClassOptions.BatchClassDefinition.Scripts.Script>();
                }
                return this.script;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileName",
                "selected"
            })
            public static class Script
                implements Serializable
            {

                private final static long serialVersionUID = 100L;
                @XmlElement(name = "FileName", required = true)
                protected String fileName;
                @XmlElement(name = "Selected", defaultValue = "false")
                protected boolean selected;

                /**
                 * Gets the value of the fileName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFileName() {
                    return fileName;
                }

                /**
                 * Sets the value of the fileName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFileName(String value) {
                    this.fileName = value;
                }

                /**
                 * Gets the value of the selected property.
                 * 
                 */
                public boolean isSelected() {
                    return selected;
                }

                /**
                 * Sets the value of the selected property.
                 * 
                 */
                public void setSelected(boolean value) {
                    this.selected = value;
                }

            }

        }

    }

}
