/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ephesoft.dcma.batch.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ephesoft.dcma.batch.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded }
     * 
     */
    public UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded createUploadLearningFilesDocTypePageTypeLastFilesToBeUploaded() {
        return new UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage }
     * 
     */
    public HocrPages.HocrPage createHocrPagesHocrPage() {
        return new HocrPages.HocrPage();
    }

    /**
     * Create an instance of {@link KVExtractionFieldPatterns.KVExtractionFieldPattern }
     * 
     */
    public KVExtractionFieldPatterns.KVExtractionFieldPattern createKVExtractionFieldPatternsKVExtractionFieldPattern() {
        return new KVExtractionFieldPatterns.KVExtractionFieldPattern();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage.Corners.Corner }
     * 
     */
    public HocrPages.HocrPage.Corners.Corner createHocrPagesHocrPageCornersCorner() {
        return new HocrPages.HocrPage.Corners.Corner();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link HOCRFile.DocumentLevelFields }
     * 
     */
    public HOCRFile.DocumentLevelFields createHOCRFileDocumentLevelFields() {
        return new HOCRFile.DocumentLevelFields();
    }

    /**
     * Create an instance of {@link CopyDocumentType.NewDocumentType }
     * 
     */
    public CopyDocumentType.NewDocumentType createCopyDocumentTypeNewDocumentType() {
        return new CopyDocumentType.NewDocumentType();
    }

    /**
     * Create an instance of {@link HeaderRow }
     * 
     */
    public HeaderRow createHeaderRow() {
        return new HeaderRow();
    }

    /**
     * Create an instance of {@link Page.PageLevelFields }
     * 
     */
    public Page.PageLevelFields createPagePageLevelFields() {
        return new Page.PageLevelFields();
    }

    /**
     * Create an instance of {@link Batch }
     * 
     */
    public Batch createBatch() {
        return new Batch();
    }

    /**
     * Create an instance of {@link com.ephesoft.dcma.batch.schema.Document.DocumentLevelFields }
     * 
     */
    public com.ephesoft.dcma.batch.schema.Document.DocumentLevelFields createDocumentDocumentLevelFields() {
        return new com.ephesoft.dcma.batch.schema.Document.DocumentLevelFields();
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType.PageTypeMiddle }
     * 
     */
    public UploadLearningFiles.DocType.PageTypeMiddle createUploadLearningFilesDocTypePageTypeMiddle() {
        return new UploadLearningFiles.DocType.PageTypeMiddle();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link com.ephesoft.dcma.batch.schema.Document.DataTables }
     * 
     */
    public com.ephesoft.dcma.batch.schema.Document.DataTables createDocumentDataTables() {
        return new com.ephesoft.dcma.batch.schema.Document.DataTables();
    }

    /**
     * Create an instance of {@link BatchClasses.BatchClass }
     * 
     */
    public BatchClasses.BatchClass createBatchClassesBatchClass() {
        return new BatchClasses.BatchClass();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage.Spans.Span }
     * 
     */
    public HocrPages.HocrPage.Spans.Span createHocrPagesHocrPageSpansSpan() {
        return new HocrPages.HocrPage.Spans.Span();
    }

    /**
     * Create an instance of {@link Modules.Module }
     * 
     */
    public Modules.Module createModulesModule() {
        return new Modules.Module();
    }

    /**
     * Create an instance of {@link UserInformation }
     * 
     */
    public UserInformation createUserInformation() {
        return new UserInformation();
    }

    /**
     * Create an instance of {@link DocField.AlternateValues }
     * 
     */
    public DocField.AlternateValues createDocFieldAlternateValues() {
        return new DocField.AlternateValues();
    }

    /**
     * Create an instance of {@link BatchInstances.BatchInstance }
     * 
     */
    public BatchInstances.BatchInstance createBatchInstancesBatchInstance() {
        return new BatchInstances.BatchInstance();
    }

    /**
     * Create an instance of {@link DocField }
     * 
     */
    public DocField createDocField() {
        return new DocField();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage.Corners }
     * 
     */
    public HocrPages.HocrPage.Corners createHocrPagesHocrPageCorners() {
        return new HocrPages.HocrPage.Corners();
    }

    /**
     * Create an instance of {@link ExtractTableParam.Documents }
     * 
     */
    public ExtractTableParam.Documents createExtractTableParamDocuments() {
        return new ExtractTableParam.Documents();
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType.PageTypeFirst }
     * 
     */
    public UploadLearningFiles.DocType.PageTypeFirst createUploadLearningFilesDocTypePageTypeFirst() {
        return new UploadLearningFiles.DocType.PageTypeFirst();
    }

    /**
     * Create an instance of {@link ExtractTableParam }
     * 
     */
    public ExtractTableParam createExtractTableParam() {
        return new ExtractTableParam();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link ExtractKVParams.Params }
     * 
     */
    public ExtractKVParams.Params createExtractKVParamsParams() {
        return new ExtractKVParams.Params();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link KVExtractionFieldPatterns }
     * 
     */
    public KVExtractionFieldPatterns createKVExtractionFieldPatterns() {
        return new KVExtractionFieldPatterns();
    }

    /**
     * Create an instance of {@link ListValues }
     * 
     */
    public ListValues createListValues() {
        return new ListValues();
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType.PageTypeLast }
     * 
     */
    public UploadLearningFiles.DocType.PageTypeLast createUploadLearningFilesDocTypePageTypeLast() {
        return new UploadLearningFiles.DocType.PageTypeLast();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition.Folders }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition.Folders createImportBatchClassOptionsBatchClassDefinitionFolders() {
        return new ImportBatchClassOptions.BatchClassDefinition.Folders();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions }
     * 
     */
    public ImportBatchClassOptions createImportBatchClassOptions() {
        return new ImportBatchClassOptions();
    }

    /**
     * Create an instance of {@link Batch.Documents }
     * 
     */
    public Batch.Documents createBatchDocuments() {
        return new Batch.Documents();
    }

    /**
     * Create an instance of {@link BatchClasses }
     * 
     */
    public BatchClasses createBatchClasses() {
        return new BatchClasses();
    }

    /**
     * Create an instance of {@link ExtractTableParam.Documents.Document }
     * 
     */
    public ExtractTableParam.Documents.Document createExtractTableParamDocumentsDocument() {
        return new ExtractTableParam.Documents.Document();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition.Folders.Folder }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition.Folders.Folder createImportBatchClassOptionsBatchClassDefinitionFoldersFolder() {
        return new ImportBatchClassOptions.BatchClassDefinition.Folders.Folder();
    }

    /**
     * Create an instance of {@link HeaderRow.Columns }
     * 
     */
    public HeaderRow.Columns createHeaderRowColumns() {
        return new HeaderRow.Columns();
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded }
     * 
     */
    public UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded createUploadLearningFilesDocTypePageTypeFirstFilesToBeUploaded() {
        return new UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded();
    }

    /**
     * Create an instance of {@link Batch.BatchLevelFields }
     * 
     */
    public Batch.BatchLevelFields createBatchBatchLevelFields() {
        return new Batch.BatchLevelFields();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage.Barcodes }
     * 
     */
    public HocrPages.HocrPage.Barcodes createHocrPagesHocrPageBarcodes() {
        return new HocrPages.HocrPage.Barcodes();
    }

    /**
     * Create an instance of {@link WebServiceParams }
     * 
     */
    public WebServiceParams createWebServiceParams() {
        return new WebServiceParams();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage.Barcodes.Barcode }
     * 
     */
    public HocrPages.HocrPage.Barcodes.Barcode createHocrPagesHocrPageBarcodesBarcode() {
        return new HocrPages.HocrPage.Barcodes.Barcode();
    }

    /**
     * Create an instance of {@link Column.AlternateValues }
     * 
     */
    public Column.AlternateValues createColumnAlternateValues() {
        return new Column.AlternateValues();
    }

    /**
     * Create an instance of {@link com.ephesoft.dcma.batch.schema.Document }
     * 
     */
    public com.ephesoft.dcma.batch.schema.Document createDocument() {
        return new com.ephesoft.dcma.batch.schema.Document();
    }

    /**
     * Create an instance of {@link HocrPages.HocrPage.Spans }
     * 
     */
    public HocrPages.HocrPage.Spans createHocrPagesHocrPageSpans() {
        return new HocrPages.HocrPage.Spans();
    }

    /**
     * Create an instance of {@link Page }
     * 
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link BatchInstances }
     * 
     */
    public BatchInstances createBatchInstances() {
        return new BatchInstances();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition.BatchClassModules }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition.BatchClassModules createImportBatchClassOptionsBatchClassDefinitionBatchClassModules() {
        return new ImportBatchClassOptions.BatchClassDefinition.BatchClassModules();
    }

    /**
     * Create an instance of {@link DataTable }
     * 
     */
    public DataTable createDataTable() {
        return new DataTable();
    }

    /**
     * Create an instance of {@link WebServiceParams.Params }
     * 
     */
    public WebServiceParams.Params createWebServiceParamsParams() {
        return new WebServiceParams.Params();
    }

    /**
     * Create an instance of {@link CopyDocumentType }
     * 
     */
    public CopyDocumentType createCopyDocumentType() {
        return new CopyDocumentType();
    }

    /**
     * Create an instance of {@link com.ephesoft.dcma.batch.schema.Document.Pages }
     * 
     */
    public com.ephesoft.dcma.batch.schema.Document.Pages createDocumentPages() {
        return new com.ephesoft.dcma.batch.schema.Document.Pages();
    }

    /**
     * Create an instance of {@link BatchLevelField }
     * 
     */
    public BatchLevelField createBatchLevelField() {
        return new BatchLevelField();
    }

    /**
     * Create an instance of {@link HOCRFile }
     * 
     */
    public HOCRFile createHOCRFile() {
        return new HOCRFile();
    }

    /**
     * Create an instance of {@link Field.CoordinatesList }
     * 
     */
    public Field.CoordinatesList createFieldCoordinatesList() {
        return new Field.CoordinatesList();
    }

    /**
     * Create an instance of {@link ReportingOptions }
     * 
     */
    public ReportingOptions createReportingOptions() {
        return new ReportingOptions();
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded }
     * 
     */
    public UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded createUploadLearningFilesDocTypePageTypeMiddleFilesToBeUploaded() {
        return new UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded();
    }

    /**
     * Create an instance of {@link UploadLearningFiles.DocType }
     * 
     */
    public UploadLearningFiles.DocType createUploadLearningFilesDocType() {
        return new UploadLearningFiles.DocType();
    }

    /**
     * Create an instance of {@link ExtractKVParams }
     * 
     */
    public ExtractKVParams createExtractKVParams() {
        return new ExtractKVParams();
    }

    /**
     * Create an instance of {@link WebServiceParams.Params.Param }
     * 
     */
    public WebServiceParams.Params.Param createWebServiceParamsParamsParam() {
        return new WebServiceParams.Params.Param();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition.Scripts.Script }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition.Scripts.Script createImportBatchClassOptionsBatchClassDefinitionScriptsScript() {
        return new ImportBatchClassOptions.BatchClassDefinition.Scripts.Script();
    }

    /**
     * Create an instance of {@link Batch.DocumentClassificationTypes }
     * 
     */
    public Batch.DocumentClassificationTypes createBatchDocumentClassificationTypes() {
        return new Batch.DocumentClassificationTypes();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule createImportBatchClassOptionsBatchClassDefinitionBatchClassModulesBatchClassModule() {
        return new ImportBatchClassOptions.BatchClassDefinition.BatchClassModules.BatchClassModule();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition.Scripts }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition.Scripts createImportBatchClassOptionsBatchClassDefinitionScripts() {
        return new ImportBatchClassOptions.BatchClassDefinition.Scripts();
    }

    /**
     * Create an instance of {@link Row.Columns }
     * 
     */
    public Row.Columns createRowColumns() {
        return new Row.Columns();
    }

    /**
     * Create an instance of {@link KVExtractionDocType }
     * 
     */
    public KVExtractionDocType createKVExtractionDocType() {
        return new KVExtractionDocType();
    }

    /**
     * Create an instance of {@link UploadLearningFiles }
     * 
     */
    public UploadLearningFiles createUploadLearningFiles() {
        return new UploadLearningFiles();
    }

    /**
     * Create an instance of {@link HocrPages }
     * 
     */
    public HocrPages createHocrPages() {
        return new HocrPages();
    }

    /**
     * Create an instance of {@link ImportBatchClassOptions.BatchClassDefinition }
     * 
     */
    public ImportBatchClassOptions.BatchClassDefinition createImportBatchClassOptionsBatchClassDefinition() {
        return new ImportBatchClassOptions.BatchClassDefinition();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link ExtractKV }
     * 
     */
    public ExtractKV createExtractKV() {
        return new ExtractKV();
    }

    /**
     * Create an instance of {@link com.ephesoft.dcma.batch.schema.Documents }
     * 
     */
    public com.ephesoft.dcma.batch.schema.Documents createDocuments() {
        return new com.ephesoft.dcma.batch.schema.Documents();
    }

    /**
     * Create an instance of {@link DataTable.Rows }
     * 
     */
    public DataTable.Rows createDataTableRows() {
        return new DataTable.Rows();
    }

}
