/********************************************************************************* 
* Ephesoft is a Intelligent Document Capture and Mailroom Automation program 
* developed by Ephesoft, Inc. Copyright (C) 2015 Ephesoft Inc. 
* 
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Affero General Public License version 3 as published by the 
* Free Software Foundation with the addition of the following permission added 
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK 
* IN WHICH THE COPYRIGHT IS OWNED BY EPHESOFT, EPHESOFT DISCLAIMS THE WARRANTY 
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. 
* 
* This program is distributed in the hope that it will be useful, but WITHOUT 
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more 
* details. 
* 
* You should have received a copy of the GNU Affero General Public License along with 
* this program; if not, see http://www.gnu.org/licenses or write to the Free 
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 
* 02110-1301 USA. 
* 
* You can contact Ephesoft, Inc. headquarters at 111 Academy Way, 
* Irvine, CA 92617, USA. or at email address info@ephesoft.com. 
* 
* The interactive user interfaces in modified source and object code versions 
* of this program must display Appropriate Legal Notices, as required under 
* Section 5 of the GNU Affero General Public License version 3. 
* 
* In accordance with Section 7(b) of the GNU Affero General Public License version 3, 
* these Appropriate Legal Notices must retain the display of the "Ephesoft" logo. 
* If the display of the logo is not reasonably feasible for 
* technical reasons, the Appropriate Legal Notices must display the words 
* "Powered by Ephesoft". 
********************************************************************************/ 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.14 at 09:01:24 PM IST 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batch_class_id" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="doc_type" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="doc_type_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="learning_type" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="page_type_first" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="files_to_be_uploaded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="page_type_middle" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="files_to_be_uploaded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="page_type_last" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="files_to_be_uploaded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchClassId",
    "docType"
})
@XmlRootElement(name = "upload_learning_files")
public class UploadLearningFiles
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "batch_class_id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String batchClassId;
    @XmlElement(name = "doc_type", required = true)
    protected List<UploadLearningFiles.DocType> docType;

    /**
     * Gets the value of the batchClassId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchClassId() {
        return batchClassId;
    }

    /**
     * Sets the value of the batchClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchClassId(String value) {
        this.batchClassId = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UploadLearningFiles.DocType }
     * 
     * 
     */
    public List<UploadLearningFiles.DocType> getDocType() {
        if (docType == null) {
            docType = new ArrayList<UploadLearningFiles.DocType>();
        }
        return this.docType;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="doc_type_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="learning_type" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="page_type_first" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="files_to_be_uploaded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="page_type_middle" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="files_to_be_uploaded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="page_type_last" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="files_to_be_uploaded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "docTypeName",
        "learningType",
        "pageTypeFirst",
        "pageTypeMiddle",
        "pageTypeLast"
    })
    public static class DocType
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "doc_type_name", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String docTypeName;
        @XmlElement(name = "learning_type", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String learningType;
        @XmlElement(name = "page_type_first")
        protected UploadLearningFiles.DocType.PageTypeFirst pageTypeFirst;
        @XmlElement(name = "page_type_middle")
        protected UploadLearningFiles.DocType.PageTypeMiddle pageTypeMiddle;
        @XmlElement(name = "page_type_last")
        protected UploadLearningFiles.DocType.PageTypeLast pageTypeLast;

        /**
         * Gets the value of the docTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocTypeName() {
            return docTypeName;
        }

        /**
         * Sets the value of the docTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocTypeName(String value) {
            this.docTypeName = value;
        }

        /**
         * Gets the value of the learningType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLearningType() {
            return learningType;
        }

        /**
         * Sets the value of the learningType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLearningType(String value) {
            this.learningType = value;
        }

        /**
         * Gets the value of the pageTypeFirst property.
         * 
         * @return
         *     possible object is
         *     {@link UploadLearningFiles.DocType.PageTypeFirst }
         *     
         */
        public UploadLearningFiles.DocType.PageTypeFirst getPageTypeFirst() {
            return pageTypeFirst;
        }

        /**
         * Sets the value of the pageTypeFirst property.
         * 
         * @param value
         *     allowed object is
         *     {@link UploadLearningFiles.DocType.PageTypeFirst }
         *     
         */
        public void setPageTypeFirst(UploadLearningFiles.DocType.PageTypeFirst value) {
            this.pageTypeFirst = value;
        }

        /**
         * Gets the value of the pageTypeMiddle property.
         * 
         * @return
         *     possible object is
         *     {@link UploadLearningFiles.DocType.PageTypeMiddle }
         *     
         */
        public UploadLearningFiles.DocType.PageTypeMiddle getPageTypeMiddle() {
            return pageTypeMiddle;
        }

        /**
         * Sets the value of the pageTypeMiddle property.
         * 
         * @param value
         *     allowed object is
         *     {@link UploadLearningFiles.DocType.PageTypeMiddle }
         *     
         */
        public void setPageTypeMiddle(UploadLearningFiles.DocType.PageTypeMiddle value) {
            this.pageTypeMiddle = value;
        }

        /**
         * Gets the value of the pageTypeLast property.
         * 
         * @return
         *     possible object is
         *     {@link UploadLearningFiles.DocType.PageTypeLast }
         *     
         */
        public UploadLearningFiles.DocType.PageTypeLast getPageTypeLast() {
            return pageTypeLast;
        }

        /**
         * Sets the value of the pageTypeLast property.
         * 
         * @param value
         *     allowed object is
         *     {@link UploadLearningFiles.DocType.PageTypeLast }
         *     
         */
        public void setPageTypeLast(UploadLearningFiles.DocType.PageTypeLast value) {
            this.pageTypeLast = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="files_to_be_uploaded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "filesToBeUploaded"
        })
        public static class PageTypeFirst
            implements Serializable
        {

            private final static long serialVersionUID = 100L;
            @XmlElement(name = "files_to_be_uploaded", required = true)
            protected UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded filesToBeUploaded;

            /**
             * Gets the value of the filesToBeUploaded property.
             * 
             * @return
             *     possible object is
             *     {@link UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded }
             *     
             */
            public UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded getFilesToBeUploaded() {
                return filesToBeUploaded;
            }

            /**
             * Sets the value of the filesToBeUploaded property.
             * 
             * @param value
             *     allowed object is
             *     {@link UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded }
             *     
             */
            public void setFilesToBeUploaded(UploadLearningFiles.DocType.PageTypeFirst.FilesToBeUploaded value) {
                this.filesToBeUploaded = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileName"
            })
            public static class FilesToBeUploaded
                implements Serializable
            {

                private final static long serialVersionUID = 100L;
                @XmlElement(name = "file_name", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected List<String> fileName;

                /**
                 * Gets the value of the fileName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the fileName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFileName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getFileName() {
                    if (fileName == null) {
                        fileName = new ArrayList<String>();
                    }
                    return this.fileName;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="files_to_be_uploaded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "filesToBeUploaded"
        })
        public static class PageTypeLast
            implements Serializable
        {

            private final static long serialVersionUID = 100L;
            @XmlElement(name = "files_to_be_uploaded", required = true)
            protected UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded filesToBeUploaded;

            /**
             * Gets the value of the filesToBeUploaded property.
             * 
             * @return
             *     possible object is
             *     {@link UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded }
             *     
             */
            public UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded getFilesToBeUploaded() {
                return filesToBeUploaded;
            }

            /**
             * Sets the value of the filesToBeUploaded property.
             * 
             * @param value
             *     allowed object is
             *     {@link UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded }
             *     
             */
            public void setFilesToBeUploaded(UploadLearningFiles.DocType.PageTypeLast.FilesToBeUploaded value) {
                this.filesToBeUploaded = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileName"
            })
            public static class FilesToBeUploaded
                implements Serializable
            {

                private final static long serialVersionUID = 100L;
                @XmlElement(name = "file_name", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected List<String> fileName;

                /**
                 * Gets the value of the fileName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the fileName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFileName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getFileName() {
                    if (fileName == null) {
                        fileName = new ArrayList<String>();
                    }
                    return this.fileName;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="files_to_be_uploaded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "filesToBeUploaded"
        })
        public static class PageTypeMiddle
            implements Serializable
        {

            private final static long serialVersionUID = 100L;
            @XmlElement(name = "files_to_be_uploaded", required = true)
            protected UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded filesToBeUploaded;

            /**
             * Gets the value of the filesToBeUploaded property.
             * 
             * @return
             *     possible object is
             *     {@link UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded }
             *     
             */
            public UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded getFilesToBeUploaded() {
                return filesToBeUploaded;
            }

            /**
             * Sets the value of the filesToBeUploaded property.
             * 
             * @param value
             *     allowed object is
             *     {@link UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded }
             *     
             */
            public void setFilesToBeUploaded(UploadLearningFiles.DocType.PageTypeMiddle.FilesToBeUploaded value) {
                this.filesToBeUploaded = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileName"
            })
            public static class FilesToBeUploaded
                implements Serializable
            {

                private final static long serialVersionUID = 100L;
                @XmlElement(name = "file_name", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected List<String> fileName;

                /**
                 * Gets the value of the fileName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the fileName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFileName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getFileName() {
                    if (fileName == null) {
                        fileName = new ArrayList<String>();
                    }
                    return this.fileName;
                }

            }

        }

    }

}
